### ISSUE TITLE
An error occurred communicating with the node -32003

### ISSUE THREAD

**Issue by MrCoolLV** [snissn/tokenpool#30]
getting this error when miners connect to pool

**Comment by torchmike** [comment]
I think that the pool is having trouble connecting to your web3 provider. 

you should either use your own full parity node, or if that is not available, use infura

**Comment by MrCoolLV** [comment]
I see, and to edit/fix that ?

**Comment by MrCoolLV** [comment]
thank you

**Comment by MrCoolLV** [comment]
Hello still getting this error even if i swapped from parity or infura

firewall is off and disabled

**Comment by MrCoolLV** [comment]
Fixed all the issues in our fork https://github.com/NocRoom/tokenpool
